
server:
  port: 8000

spring:
  application:
    name: SERVER-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/karthikeyan-velmurugan/springboot-microservice
          clone-on-start: true  
   